### ISSUE TITLE
Come up with an alternative for helix potential or implement new force in OpenMM

### ISSUE THREAD

**Issue by npschafer** [npschafer/openawsem#10]

**Comment by agrossfield** [comment]
I'm looking at using AWSEM. I'm far more familiar with OpenMM than LAMMPS, but the missing helix term is a bit confusing. Is the OpenMM version usable and correct, or should I go with LAMMPS?

**Comment by npschafer** [comment]
Unfortunately, the alpha-helical hydrogen-bonding potential lies just outside of what is currently possible to implement in OpenMM's custom forces framework because it is both density-dependent and involves the interaction of three atoms in the pairwise part of the potential (to ensure that both the distance and the angle are appropriate for a hydrogen bond). Fortunately, the alpha-helical hydrogen-bonding potential is not the only potential in AWSEM that contains helical signals. For most of its history, the AWSEM family of potentials relied on the associative memory potential (also sometimes called the fragment memory potential) to capture local-in-sequence signals. The alpha-helical hydrogen-bonding potential was introduced as a possible means of replacing the (non-transferrable) associative memory potential with a fully transferrable potential for alpha-helical proteins. [The paper that introduced the potential](https://www.sciencedirect.com/science/article/pii/S1046202310001507) showed that the alpha-helical hydrogen bonding potential by itself is not always a good substitute for the associative memory potential. In short, for most purposes, it should be fine to use OpenAWSEM with the associative memory potential even if you are interested in simulating alpha-helical proteins. If you are familiar with OpenMM and not very familiar with LAMMPS, then I would say that OpenAWSEM is the better choice, especially if you have access to GPUs and are interested in large or very long simulations. If you are familiar with OpenMM's custom forces framework, you could even implement your own (non-density-dependent) alpha-helical hydrogen bonding potential. Let me know if you disagree with anything that I said @luwei0917 or @cabb99, and thanks for your interest @agrossfield.

**Comment by agrossfield** [comment]
Ok, that’s reassuring. The system I’m interested in isn’t particularly helical, so I’ll take a look at this to start.

Cheers,

Alan
