### ISSUE TITLE
Implementation of non-additive amhgo potential term 

### ISSUE THREAD

**Issue by yihengwuKP** [npschafer/openawsem#18]
**Feature Request**
Can we have a non-additive amhgo potential term in `OpenAWSEM`?  I am trying to reproduce [Bin Zhang's work on Nucleosomes](https://pubs.acs.org/doi/abs/10.1021/jacs.6b02893) in `OpenMM`, but found that the amhgo potential he used is a non-additive one, with  the power p equals 2.5. In current version of `OpenAWSEM`, I only found an `additive_amhgo_term` in [`templateTerms.py`](https://github.com/npschafer/openawsem/blob/master/functionTerms/templateTerms.py), which corresponds to power p = 1. Is it possible for requesting an implementation of non-additive amhgo in `OpenMM`? Or is it very difficult under the constrain of `OpenMM API`?

**Comment by npschafer** [comment]
I think that we looked into this awhile back and didn't find an efficient way to implement it with OpenMM's various Custom Forces. Does that sound right @luwei0917?

**Comment by luwei0917** [comment]
I think we could use collective variable (CustomCVForce(f"0.5*abs(E)^p")) to achieve this non-additiveness. you can find an example at the qbias_term in qBiasTerms.py.  Let me know if you need any additional help.

**Comment by cabb99** [comment]
I added an implementation of the non-additive go potential following Wei suggestion as an [example ](https://github.com/npschafer/openawsem/tree/master/examples/non_additive_go) . The code can be found in the [force_setup.py](https://github.com/npschafer/openawsem/blob/master/examples/non_additive_go/forces_setup.py) file. It still needs some work to set the parameters correctly and make it faster, but I think it is a good starting point.

**Comment by yihengwuKP** [comment]
Also, reporting a bug @cabb99, when I execute `./mm_run.py 1r69 -p CUDA` or `./mm_run.py 1r69 -p OpenCL` under the `example/non_additive_go` folder, the following Exception is thrown: 
```python
Traceback (most recent call last):
  File "./mm_run.py", line 163, in <module>
    simulation = Simulation(oa.pdb.topology, oa.system, integrator, platform)
  File "/home/yihengwu917/.conda/envs/dinucl/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
  File "/home/yihengwu917/.conda/envs/dinucl/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: All Forces must have identical exceptions
```
The CPU platform and the reference platform work on perfectly! Is this related to the platform-dependent Exclusion that I saw in [`Protein_DNA_example.py`](https://github.com/cabb99/open3spn2/blob/master/examples/Protein_DNA/Protein_DNA_example.py) line 130? (Where for CPU and reference use_exlusion=True but for Cuda and OpenCL use_exclusion=False) But I am not sure.
