### ISSUE TITLE
Inconsistency for beta hydrogen bond potential between openawsem and awsemmd

### ISSUE THREAD

**Issue by smliu1997** [npschafer/openawsem#19]
Hi, I have one question about hydrogen bond potential. So from AWSEM-MD paper SI (https://pubs.acs.org/doi/10.1021/jp212541y), the expression of beta-hydrogen bond is: 
<img width="908" alt="image" src="https://user-images.githubusercontent.com/71535756/191555073-3c58a3b9-335a-4d69-96a9-98f0027e6733.png">
And $\Lambda_3$ is expressed as:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/71535756/191555229-3e395549-0acf-491e-98b4-1d6a74031bbd.png">
However, the expression for $\Lambda_3$ in openawsem is:
https://github.com/npschafer/openawsem/blob/92a93631b919d470a4d3d67dff63dd9fddfb373b/functionTerms/hydrogenBondTerms.py#L152-L157

And in awsemmd, the related code (https://github.com/adavtyan/awsemmd/blob/master/src/fix_backbone.cpp) is in line 2792-2800 and 2804-2812:
```
      lambda[0] = -hbscl[2][0];
      lambda[1] = -hbscl[2][1];
      lambda[2] = -hbscl[2][2]
	-hbscl[2][3]*theta_seq_anti_HB[1]
	-hbscl[2][4]*theta_seq_anti_NHB[1]
	-hbscl[2][5]*(anti_one(se[i_resno])+anti_one(se[j_resno]));
      lambda[3] = -hbscl[2][6]
	-hbscl[2][7]*theta_seq_para_HB[1]
	-hbscl[2][8]*(para_one(se[i_resno+1])+para_one(se[j_resno]));
```

```
    lambda[0] = -hbscl[3][0];
    lambda[1] = -hbscl[3][1];
    lambda[2] = -hbscl[3][2]
      -hbscl[3][3]*theta_seq_anti_HB[1]
      -hbscl[3][4]*theta_seq_anti_NHB[1]
      -hbscl[3][5]*(anti_one(se[i_resno])+anti_one(se[j_resno]));
    lambda[3] = -hbscl[3][6]
      -hbscl[3][7]*theta_seq_para_HB[1]
      -hbscl[3][8]*(para_one(se[i_resno+1])+para_one(se[j_resno]));
```
So in all, the expression for the $\Lambda_3$ in the paper SI, openawsem, and awsemmd are not consistent. So I wonder for the final term in $\Lambda_3$ expression in the paper, whether it should be $\alpha_4 \ln P_{par}(a_j)$ or $\alpha_5 \ln P_{par}(a_j)$, and whether it should be plus or minus sign? Thank you so much!

**Comment by smliu1997** [comment]
And actually there is one more follow-up question, still for the expressions of $\Lambda_2$ and $\Lambda_3$. So these are the expressions from the paper:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/71535756/191558488-7b50395a-9427-4331-8ce9-2662cade961e.png">
And you can see for $\Lambda_2$, the expression includes plus sign before $\lambda_2$, but other terms have minus sign. But in awsemmd code, all the terms for $\Lambda_2$ have the minus sign. Similar issue exists for $\Lambda_3$, so I wonder if there is typo in the paper, or the code has bug. Openawsem seems to follow the paper expression for $\Lambda_2$ and $\Lambda_3$. Thanks!

**Comment by luwei0917** [comment]
Hello, thanks for the careful comparison. It looks like we use get_alpha_by_index(i, j, 4) to mean alpha_5 because python indexing typically starts from zero instead of 1.

The plus/minus sign could be absorbed by the lnP(a) constant. 

I think we checked the energy difference between OpenAWSEM and AWSEM-MD, they should be consistent. 
Please let me know if you have any further question. Thanks.

**Comment by smliu1997** [comment]
Hi Wei, thank you so much for your reply! Yes, I agree that openawsem seems to follow the formula given by the paper, but only different from the paper by a minus sign
```
 def get_Lambda_3(i, j, p_par, p_anti, p_antihb, p_antinhb, p_parhb, a): 
     Lambda = get_lambda_by_index(i, j, 2) 
     Lambda += -get_alpha_by_index(i, j, 3)*p_parhb[a[i+1], a[j]][0] 
     Lambda += -get_alpha_by_index(i, j, 4)*p_par[a[i+1]] 
     Lambda += -get_alpha_by_index(i, j, 3)*p_par[a[j]] 
     return Lambda 
```
So if following the paper, the fifth line should be `Lambda += get_alpha_by_index(i, j, 3)*p_par[a[j]] `.
Meanwhile, if following lammps code (and if I understand lammps awsemmd code correctly), the fifth line should be 
```
Lambda += -get_alpha_by_index(i, j, 4)*p_par[a[j]]
```
so basically the paper, openawsem, and awsemmd seem to give inconsistent things here, so not sure which one is correct.

**Comment by luwei0917** [comment]
I see you point. I think this is an implementation error on the awsemmd version. (Thanks for pointing this out, I didn't notice this before)
although luckily hbscl[3][8] is the same as hbscl[2][7], so the result should be the same.

https://github.com/adavtyan/awsemmd/blob/03babaa2f0b03e7ed20fe1016d83747f7442a5d5/parameters/fix_backbone_coeff.data#L42

Hope this resolve your question. please let me know if not.

**Comment by aramdbs** [comment]
@smliu1997 It should indeed be -get_alpha_by_index(i, j, 3)*p_par[a[j]] on openAWSEM side. And in the paper, it is also a type, where one should have -a5 in the last expression in front of the lnP_par(aj)

**Comment by cabb99** [comment]
@MengyanWang checked this and it is true there is a small difference for proteins containing beta sheets. It should be corrected now. Thanks @aramdbs
