### ISSUE TITLE
Stride not available

### ISSUE THREAD

**Issue by mengqvist** [npschafer/openawsem#25]
It seems that stride is no longer available through pip. Nor do the wget installation instructions provided in the README work.
Also their webpage seems to be down. http://webclu.bio.wzw.tum.de/stride/

Is it possible to install OpenAWSEM without this library?

**Comment by cabb99** [comment]
Yes, it should also work with DSSP. But stride is a really popular package that can be found in other projects. https://github.com/MDAnalysis/stride/tree/master/src

**Comment by mengqvist** [comment]
Thanks! Would be good to put that link in the README.

Regardless I'll see if I can get a workaround going that does not rely on Stride.
